### ISSUE TITLE
Repository url is incorrect

### ISSUE THREAD

**Issue by michael-stevens** [KeitaMoromizato/mysql-to-bigquery#1]
Repository URL is set in package.json to:

```
 "repository": {
    "type": "git",
    "url": "https://github.com/KeitaMoromizato/textlint-rule-ja-yahoo-kousei.git"
```

This looks like it's actually one of your other projects.

**Comment by KeitaMoromizato** [comment]
Oh...
I published version v 1.0.13. Thanks.
https://github.com/KeitaMoromizato/mysql-to-bigquery/pull/2
